#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Feb 17, 2019 09:34:03 AM


import sys
import sqlite3
import os
import adminpanel
try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def checkadmindb(username1,pass1):
     if username1=='admin' or username1=='nikhil':
        connector=sqlite3.connect("admin.db")
        c=connector.cursor()
        query="select * from login  where username="+"'"+username1+"'"
        #print(query)
        c.execute(query)
        row=c.fetchone()
        #print(row)
        #print(user)
        if username1==row[0] and pass1==row[1]:
            print("Login Successful")
            #adminpanel.main()
            os.system("adminpanel.py")
        else:
            print("Login Failed")
    
    
def checkdb(user2,pass2):
    connector=sqlite3.connect("customer.db")
    c=connector.cursor()
    query="select * from login where username="+"'"+user2+"'"
    c.execute(query)
    row=c.fetchone()
    if user2==row[0] and pass2==row[1]:
        os.system("customerpanel.py")

def validate():
    #print('supermarket_support.validate')
    user_name=w.Entry1.get()
    password=w.Entry2.get()
    #print(user_name)
    #print(password)
    if user_name=='admin' or user_name=='nikhil':
            checkadmindb(user_name,password)
    else:
        checkdb(user_name,password)
        
    
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import supermarket
    supermarket.vp_start_gui()

