#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Feb 17, 2019 09:26:37 AM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import supermarket_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Login_ (root)
    supermarket_support.init(root, top)
    root.mainloop()

w = None
def create_Login_(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Login_ (w)
    supermarket_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Login_():
    global w
    w.destroy()
    w = None


class Login_:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font9 = "-family Arial -size 12 -weight normal -slant roman "  \
            "-underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("600x450+459+235")
        top.title("Login ")
        top.configure(background="#d80404")



        self.Label1 = Label(top)
        self.Label1.place(relx=0.22, rely=0.11, height=29, width=344)
        self.Label1.configure(background="#5bd8c7")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''LOGIN TO SUPERMARKET SYSTEM''')

        self.Label2 = Label(top)
        self.Label2.place(relx=0.22, rely=0.29, height=23, width=125)
        self.Label2.configure(background="#74d85b")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Enter Username :''')

        self.Entry1 = Entry(top)
        self.Entry1.place(relx=0.43, rely=0.29,height=24, relwidth=0.34)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")

        self.Label3 = Label(top)
        self.Label3.place(relx=0.22, rely=0.4, height=23, width=123)
        self.Label3.configure(background="#74d85b")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''Enter Password :''')

        self.Entry2 = Entry(top)
        self.Entry2.place(relx=0.43, rely=0.4,height=24, relwidth=0.34)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(insertbackground="black")

        self.TButton1 = ttk.Button(top)
        self.TButton1.place(relx=0.35, rely=0.53, height=57, width=178)
        self.TButton1.configure(takefocus="")
        self.TButton1.configure(text='''Login''')
        self.TButton1.configure(width=178)






if __name__ == '__main__':
    vp_start_gui()



